# .github/workflows/main.yml

name: Devops CI pipeline 

on:
  pull_request:
    branches:
       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
       node-version: 16.10.0

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint


    - name: Install prettier
      run: npm install -g prettier

    - name: Run prettier
      run: npm run prettier
  
    - name: Run Test
      run: CI=true npm run test

    - name: Build
      run: npm run build


  

